In [ ]:
#Importing package numpy
import numpy as np 

In [ ]:
#Creating simple 1D array from a list
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#Looking at different aspects of created array

#dimenssions with ndim method #return number of dimensions
print(arr.ndim)
#shape of the array with shape method
print(arr.shape)
#size of the array or total number of elements with size method
print(arr.size)
#No of bytes needs to move for changing position with strides method
#print(arr.strides)
#type of the python object with type()
print(type(arr))
#memory location of the array with data method
print(arr.data)

1
(14,)
14
<class 'numpy.ndarray'>


In [ ]:
#Broadcasting of array elements for arithmatics

#Calculate BMI of cricket

#Heights of the players in inches 
height_inches = [61,65,63,69,70,73,68,64,63,62,66]
print(height_inches)
#Convert this to numpy array
ht_np = np.array(height_inches)
print(ht_np)
#Convert height from inch to meters by exposing it to 0.0245
ht_np = ht_np * 0.0254
ht_np

[61, 65, 63, 69, 70, 73, 68, 64, 63, 62, 66]
[61 65 63 69 70 73 68 64 63 62 66]


array([1.5494, 1.651 , 1.6002, 1.7526, 1.778 , 1.8542, 1.7272, 1.6256,
       1.6002, 1.5748, 1.6764])

In [ ]:
l = [1,2,3,4,5]
print(l*2)
l_m = [w*2 for w in l]
print(l_m)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]


In [ ]:
#Weight of players in pounds
weight_pounds = [100,200,160,180,140,155,165,172,180,200,168]

#Convert this to numpy array
wt_np = np.array(weight_pounds)

#Convert weight from pounds to kgs by exposing it to 0.45
wt_np = wt_np * 0.45
wt_np

array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [ ]:
#BMI Calculation
# formula - bmi = weight in kgs / (height in meters ** 2)
bmi = wt_np / (ht_np ** 2)
bmi

array([20.1474773 , 35.48817184, 30.22172356, 28.3435777 , 21.41964658,
       21.80551373, 26.75139684, 31.48102353, 33.99943901, 39.0055999 ,
       28.91357251])

In [ ]:
#Subsetting of arrays with index
bmi[0]

20.147477295192218

In [ ]:
#Boolean based subsetting - try to get players with BMI less than 21
bmi[bmi < 21]

array([20.1474773])

In [ ]:
#Slicing of arrays
bmi[0:4]

array([20.1474773 , 35.48817184, 30.22172356, 28.3435777 ])

In [ ]:
arr=[1,2,3,4,5,6,7,8]
arr[3:]

[1, 2, 3, 4, 5]

In [ ]:
#Making 2D array with data from arrays we created for players where one row will be height and other will be weight
players = np.array([wt_np,ht_np])
players

array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 74.25  ,
        77.4   , 81.    , 90.    , 75.6   ],
       [ 1.5494,  1.651 ,  1.6002,  1.7526,  1.778 ,  1.8542,  1.7272,
         1.6256,  1.6002,  1.5748,  1.6764]])

In [ ]:
#Looking at height and weight of the player at index 2
players[0][2],players[1][2]

(72.0, 1.6001999999999998)

In [ ]:
#Looking at height of all the players, fetching height
players[1]

array([1.5494, 1.651 , 1.6002, 1.7526, 1.778 , 1.8542, 1.7272, 1.6256,
       1.6002, 1.5748, 1.6764])

In [ ]:
#Transpose - lets transpose the array of players#row to column and column to row
pT = players.transpose()
pT
#pT.shape

array([[45.    ,  1.5494],
       [90.    ,  1.651 ],
       [72.    ,  1.6002],
       [81.    ,  1.7526],
       [63.    ,  1.778 ],
       [69.75  ,  1.8542],
       [74.25  ,  1.7272],
       [77.4   ,  1.6256],
       [81.    ,  1.6002],
       [90.    ,  1.5748],
       [75.6   ,  1.6764]])

In [ ]:
pT = players.transpose()
pT

array([[45.    ,  1.5494],
       [90.    ,  1.651 ],
       [72.    ,  1.6002],
       [81.    ,  1.7526],
       [63.    ,  1.778 ],
       [69.75  ,  1.8542],
       [74.25  ,  1.7272],
       [77.4   ,  1.6256],
       [81.    ,  1.6002],
       [90.    ,  1.5748],
       [75.6   ,  1.6764]])

In [ ]:
#Swap axes - Just like transpose but parameters needs to be defined explicitly - array and axes to be swapped
pT = np.swapaxes(pT,0,1)
pT

array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 74.25  ,
        77.4   , 81.    , 90.    , 75.6   ],
       [ 1.5494,  1.651 ,  1.6002,  1.7526,  1.778 ,  1.8542,  1.7272,
         1.6256,  1.6002,  1.5748,  1.6764]])

https://www.geeksforgeeks.org/numpy-swapaxes-function-python/

In [ ]:
#Universal functions

#Unary functions

#arange and reshape
# arr1 = np.arange(10).reshape(2,5)
# print(arr1)
#square root function
arr1=[1,2,3,4,5,6,7,8]
arr2 = np.sqrt(arr1)
print(arr2)

#Exponential function
arr3 = np.exp(arr1)
print(arr3)

#Binary Functions - check the maximum out of two arrays
arr5 = np.maximum(arr2,arr3)
print(arr5)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]


In [ ]:
#Mathematical and statistical functions

#mean function - find out mean of the weight of the players
print(np.mean(wt_np))

#median function - find out median of the weight of the players
print(np.median(wt_np))

#Sum function - find out sum of the weight of the players
print(np.sum(wt_np))

#standard devaition - find out standard deviation of the weight of the players
print(np.std(wt_np))

#Correlation coefficient - find out correlation between weight and height of the players
print(np.corrcoef(wt_np,ht_np))

74.45454545454545
75.60000000000001
819.0
12.082941667443528
[[ 1.         -0.01706933]
 [-0.01706933  1.        ]]


In [ ]:
#Methods for boolean arrays
bools = [False,True,False,False,True]

b = np.array(bools)
print(b)
#Sum method over boolean arrays
#print(b.sum())

#any method
print(b.any())

#all method
print(b.all())

[False  True False False  True]
True
False


In [ ]:
#Sort method

arr = np.random.randn(10).reshape(2,5)
print(arr)
print(np.sort(arr))

[[-0.45777881  0.87258046  0.58682695  0.16044107  0.61622244]
 [-0.71177286  1.63876182  0.30322322  0.36358766 -0.96567971]]
[[-0.45777881  0.16044107  0.58682695  0.61622244  0.87258046]
 [-0.96567971 -0.71177286  0.30322322  0.36358766  1.63876182]]


In [ ]:
#Unique Function
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [ ]:
#Ravel
arr4 = np.arange(10).reshape(2,5)
print(arr4)
rav1 = arr4.ravel()
print(rav1)
rav1[0] = 1000
print(rav1)
print(arr4)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[1000    1    2    3    4    5    6    7    8    9]
[[1000    1    2    3    4]
 [   5    6    7    8    9]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
file = open("/content/drive/MyDrive/areas.csv")
 
for i in file:
    print(i)

area

1000

1500

2300

3540

4120

4560

5490

3460

4750

2300

9000

8600

7100



In [ ]:
 
# using loadtxt()
arr = np.loadtxt("/content/drive/MyDrive/areas.csv",dtype=str)
display(arr)

array(['area', '1000', '1500', '2300', '3540', '4120', '4560', '5490',
       '3460', '4750', '2300', '9000', '8600', '7100'], dtype='<U4')

In [ ]:
#Flatten
#arr4 = np.arange(10).reshape(2,5)
#print(arr4)
#fl1 = arr4.flatten()
#print(fl1)
#fl1[0] = 1000
#print(fl1)
#print(arr4)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[1000    1    2    3    4    5    6    7    8    9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#Concatenation

# ar1 = np.arange(10).reshape(2,5)
# ar2 = np.arange(10).reshape(2,5)

# print(np.concatenate([ar1,ar2], axis = 0))
# print(np.concatenate([ar1,ar2], axis = 1))
# print(np.vstack([ar1,ar2]))
# print(np.hstack([ar1,ar2]))

In [ ]:
#Split
# arr = np.random.randn(5, 2)
# print("Original array.")
# print(arr)
# print("\n")
# first, second, third = np.split(arr, [1,3])
# print("The first split")
# print(first)
# print("\n")
# print("The second split")
# print(second)
# print("\n")
# print("The third split")
# print(third)
# print("\n")

In [ ]:
#Repeat
# arr = np.arange(3)
# print(arr)
# print("\n")
# print(arr.repeat(4))

#We can pass list as argument for repeat
# print("\n")
# print(arr.repeat([2, 3, 4]))
# print("\n")

#We can specify axes to do the repeat
# arr_2 = np.random.randn(2, 2)
# print(arr_2)
# print("\n")
# print(arr_2.repeat(2, axis=1))
# print(arr_2.repeat(2, axis=0))

In [ ]:
#Tile
# print(np.tile(arr_2, 2)) #tiling at axis = 1 i.e. on columns
# print("\n")
# print(np.tile(arr_2, (2, 1))) #tiling on rows and columns 
# print("\n")
# print(np.tile(arr_2, (3, 2))) #tiling on rows and columns 