**1) Creating a Vector**

In [ ]:
#Load Library
import numpy as np

#Create a vector as a Row
vector_row = np.array([1,2,3])

#Create vector as a Column
vector_column = np.array([[1],[2],[3]])

In [ ]:
vector_row

array([1, 2, 3])

In [ ]:
vector_column

array([[1],
       [2],
       [3]])

In [ ]:
myArr = np.zeros((2,3))
print(myArr)

[[0. 0. 0.]
 [0. 0. 0.]]


**2) Creating a Matrix**

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.zeros([4, 3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Finding the max and min values**

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Return the max element
print(np.max(matrix))
#Return the min element
print(np.min(matrix))
#To find the max element in each column
print(np.max(matrix,axis=0))
#To find the max element in each row
print(np.max(matrix,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[7 8 9]
[3 6 9]


**Calculating Average, Variance and Standard deviation**

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Mean
print(np.mean(matrix))
#Standard Dev.
print(np.std(matrix))
#Variance
print(np.var(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
2.581988897471611
6.666666666666667


**Reshaping Arrays**

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Reshape
print(matrix.reshape(9,1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**Transposing a vector or a Matrix**

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Transpose the matrix
print(matrix.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])

In [ ]:
a1D

array([1, 2, 3, 4])

In [ ]:
a2D

array([[1, 2],
       [3, 4]])

**Empty**

In [ ]:
myArr = np.empty((3,3))
print(myArr)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


**Slicing**

In [ ]:
#create numpy array
arr = np.array([3, 5, 7, 9, 11, 15, 18, 22])
arr

array([ 3,  5,  7,  9, 11, 15, 18, 22])

In [ ]:
#use slicing a 1D array
arr2 = arr[1:6]
arr2

array([ 5,  7,  9, 11, 15])

In [ ]:
# Slice Starting from 3rd value to end
arr2 = arr[3:]
arr2

array([ 9, 11, 15, 18, 22])

In [ ]:
# Slice 0 to 4 index
arr2 = arr[:5]
arr2

array([ 3,  5,  7,  9, 11])

In [ ]:
#  Use negative slicing
arr2 = arr[-4:]
arr2

array([11, 15, 18, 22])

In [ ]:
# Example 6: Use step value
arr2 = arr[::3]
arr2

array([ 3,  9, 18])

In [ ]:
# Example 7: Use slicing with interval
arr2 = arr[3::4]
arr2

array([ 9, 22])

In [ ]:
#Random Function 
a=np.random.random((15))
print(a)

[0.88298002 0.6741845  0.63612358 0.36456621 0.31461605 0.68196434
 0.48164643 0.62711802 0.5899094  0.48324072 0.22042031 0.64086472
 0.89786773 0.74802465 0.4406354 ]


In [ ]:
#Reshape function
a=np.random.random((15))
print(a)
A=a.reshape(3,5)
print(A)

[0.04231485 0.04627218 0.10519012 0.49125524 0.44486748 0.12807179
 0.79319706 0.30738507 0.9105536  0.27670405 0.02717099 0.25748601
 0.04794466 0.53788471 0.64267046]
[[0.04231485 0.04627218 0.10519012 0.49125524 0.44486748]
 [0.12807179 0.79319706 0.30738507 0.9105536  0.27670405]
 [0.02717099 0.25748601 0.04794466 0.53788471 0.64267046]]


In [ ]:
a=np.random.random((15)) 
print(a) 
A=a.reshape(3,6) 
print(A)

[0.64197295 0.34864974 0.97190814 0.36472777 0.54046977 0.05513857
 0.15514951 0.54957152 0.40368426 0.33420712 0.39516842 0.79754447
 0.7615815  0.52110549 0.91117181]


ValueError: ignored

In [ ]:
a=np.random.random((15))
print(a)
a.shape = (3, 5)
print(a)

[0.63132793 0.0525998  0.42443333 0.41936699 0.51063352 0.63768737
 0.1038478  0.85204526 0.1548085  0.71460081 0.63274845 0.52348415
 0.43380056 0.0999219  0.09339494]
[[0.63132793 0.0525998  0.42443333 0.41936699 0.51063352]
 [0.63768737 0.1038478  0.85204526 0.1548085  0.71460081]
 [0.63274845 0.52348415 0.43380056 0.0999219  0.09339494]]


In [ ]:
#Transpos function
a=np.random.random((12))
A=a.reshape(3,4)
print(A)
print(A.transpose())

[[0.01561774 0.69107451 0.76296873 0.37437034]
 [0.02766229 0.90677573 0.73148756 0.55473858]
 [0.15694346 0.01096215 0.6186296  0.81697067]]
[[0.01561774 0.02766229 0.15694346]
 [0.69107451 0.90677573 0.01096215]
 [0.76296873 0.73148756 0.6186296 ]
 [0.37437034 0.55473858 0.81697067]]


In [ ]:
#Looping in arrays
a = np.arange(0,60,5)
a = a.reshape(3,4)

print (a)


for x in np.nditer(a):
   print (x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [ ]:
#looping
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print (a) 
  
 
b = a.T 
print (b) 
 
  
for x in np.nditer(b): 
   print (x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [ ]:
#Matrix multiplication
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,1,1], [0,1,0], [1,1,1]])
print("Matrix A is:\n",A)
print("Matrix A is:\n",B)
C = np.matmul(A,B)

print("Matrix multiplication of matrix A and B is:\n",C)

Matrix A is:
 [[1 2 3]
 [4 5 6]]
Matrix A is:
 [[1 1 1]
 [0 1 0]
 [1 1 1]]
Matrix multiplication of matrix A and B is:
 [[ 4  6  4]
 [10 15 10]]


In [ ]:
# Python program to multiply two matrices using a list

# take first matrix
A = [[1, 1, 1, 1],
     [1, 1, 1, 1],
     [1, 1, 1, 1],
     [1, 1, 1, 1]]

# take second matrix
B = [[5, 5, 5, 5],
     [4, 4, 4, 4],
     [3, 3, 3, 3],
     [2, 2, 2, 2]]

# multiply matrix
res = [[sum(a * b for a, b in zip(A_row, B_col))
        for B_col in zip(*B)] for A_row in A]
for r in res:
   print(r)

[14, 14, 14, 14]
[14, 14, 14, 14]
[14, 14, 14, 14]
[14, 14, 14, 14]


In [ ]:
C = np.matmul(A,B)

In [ ]:
C

257.16911882154955