#### Importing Numpy

In [1]:
import numpy as np

Creating Blank Arrays

In [2]:
# Creating a blank array
a = np.array([])
print(a)

[]


Creating an array of 5 elements

In [3]:
# Creating an array 5 elements
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


Creating an array of 5 elements with 2 dimensions

In [4]:
# Creating an array of 5 elements with 2 dimensions
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Creating an numpy array with pattern specified data

In [5]:
# Creating an numpy array with pattern specified data
a = np.arange(10)
print(a)

a = np.arange(10, 20)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


##### Slicing and Updating Arrays

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[1:5]

array([2, 3, 4, 5])

In [7]:
# update the value of 5th element
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[4] = 50
print(arr)

[ 1  2  3  4 50  6  7  8  9 10]


In [1]:
import numpy as np
import time

start_time = time.time()

a = np.ones(shape=(1000, 1000))
b = np.ones(shape=(1000, 1000))

np.matmul(a, b)

end_time = time.time()

print("Run time = {}".format(end_time - start_time))

start_time = time.time()

X = [[1]*1000]*1000
Y = [[1]*1000]*1000
result = [[1]*1000]*1000

for i in range( len(X) ):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

end_time = time.time()

print("Run time = {}".format(end_time - start_time))

Run time = 0.22872591018676758
Run time = 341.1989572048187
